name: tuna
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.12
  - pytorch=1.13.1
  - cudatoolkit=11.6
  - pip=23.3
  - pip:
    - git+https://github.com/jlparkI/uncertaintyAwareDeepLearn@0.0.5    
    - torchvision==0.14.1
    - torchaudio==0.13.1
    - numpy==1.23.5
    - pandas==2.1.1
    - matplotlib==3.8.0
    - scikit-learn==1.3.1
    - uncertainty-calibration
    - fair-esm==2.0.0
    - PyYAML